[package]
name = "rong"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
structopt = { version = "0.3" }
pnet = { version = "0.28" }
pnet_macros_support = "0.28"
